# Generated by Django 5.2 on 2025-04-09 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Светлая тема'), ('dark', 'Темная тема'), ('auto', 'Системная настройка')], default='light', max_length=10, verbose_name='Тема оформления')),
                ('font_size', models.CharField(choices=[('small', 'Мелкий шрифт'), ('medium', 'Средний шрифт'), ('large', 'Крупный шрифт')], default='medium', max_length=10, verbose_name='Размер шрифта')),
                ('layout', models.CharField(choices=[('default', 'Стандартный макет'), ('compact', 'Компактный макет'), ('wide', 'Широкий макет')], default='default', max_length=10, verbose_name='Макет интерфейса')),
                ('enable_animations', models.BooleanField(default=True, verbose_name='Включить анимации')),
                ('high_contrast', models.BooleanField(default=False, verbose_name='Высокий контраст')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interface', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки интерфейса',
                'verbose_name_plural': 'Настройки интерфейса',
            },
        ),
    ]
