# Generated by Django 5.2 on 2025-04-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Относительный вес теста при подсчете баллов', verbose_name='Вес теста'),
        ),
    ]
