# Generated by Django 5.2 on 2025-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0002_testcase_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('testing', 'Тестируется'), ('accepted', 'Принято'), ('partial', 'Частично верно'), ('wrong_answer', 'Неправильный ответ'), ('time_limit', 'Превышено время выполнения'), ('memory_limit', 'Превышен лимит памяти'), ('runtime_error', 'Ошибка выполнения'), ('compilation_error', 'Ошибка компиляции'), ('system_error', 'Системная ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
