# Generated by Django 5.2 on 2025-04-10 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_certificatetemplate_course_difficulty_level_and_more'),
        ('olympiads', '0004_remove_problem_olympiad_remove_submission_problem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiadinvitation',
            options={'verbose_name': 'Приглашение на олимпиаду', 'verbose_name_plural': 'Приглашения на олимпиаду'},
        ),
        migrations.AlterUniqueTogether(
            name='olympiadinvitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='olympiadinvitation',
            name='code',
            field=models.CharField(default='00000000000000000000000000000000', max_length=32, unique=True, verbose_name='Код приглашения'),
        ),
        migrations.AddField(
            model_name='olympiadinvitation',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='olympiadinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия до'),
        ),
        migrations.AddField(
            model_name='olympiadinvitation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='olympiadinvitation',
            name='max_uses',
            field=models.PositiveIntegerField(default=0, help_text='0 означает без ограничений', verbose_name='Максимальное количество использований'),
        ),
        migrations.AddField(
            model_name='olympiadinvitation',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано'),
        ),
        migrations.AddField(
            model_name='olympiadtask',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiad_tasks', to='courses.course', verbose_name='Связанный курс'),
        ),
        migrations.AddField(
            model_name='olympiadtask',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, help_text='Уровень сложности от 1 до 5', verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='olympiadtask',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 означает без ограничения', verbose_name='Максимальное количество попыток'),
        ),
        migrations.AddField(
            model_name='olympiadtask',
            name='topic',
            field=models.CharField(blank=True, help_text='Тематика задания для группировки', max_length=255, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='olympiadtask',
            name='use_latex',
            field=models.BooleanField(default=False, help_text='Включить поддержку математических формул в формате LaTeX', verbose_name='Использовать LaTeX'),
        ),
        migrations.AddField(
            model_name='olympiadtask',
            name='use_markdown',
            field=models.BooleanField(default=True, help_text='Отображать описание с поддержкой Markdown', verbose_name='Использовать Markdown'),
        ),
        migrations.RemoveField(
            model_name='olympiadinvitation',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='olympiadinvitation',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='olympiadinvitation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='olympiadinvitation',
            name='user',
        ),
        migrations.CreateModel(
            name='OlympiadUserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_olympiad_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to='olympiads.olympiad', verbose_name='Олимпиада')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приглашение пользователю',
                'verbose_name_plural': 'Приглашения пользователям',
                'unique_together': {('olympiad', 'user')},
            },
        ),
    ]
