# Generated by Django 5.2 on 2025-04-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0005_alter_olympiadinvitation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Код приглашения'),
        ),
    ]
