# Generated by Django 5.2 on 2025-04-09 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(default=dict, verbose_name='Макет')),
                ('theme', models.CharField(default='light', max_length=30, verbose_name='Тема')),
                ('animation_speed', models.CharField(default='normal', max_length=20, verbose_name='Скорость анимации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Макет дашборда',
                'verbose_name_plural': 'Макеты дашборда',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('courses_progress', 'Прогресс по курсам'), ('achievements', 'Достижения'), ('recent_activity', 'Недавняя активность'), ('statistics', 'Статистика'), ('leaderboard', 'Таблица лидеров'), ('upcoming_lessons', 'Предстоящие уроки'), ('goals', 'Цели обучения'), ('study_time', 'Время обучения'), ('calendar', 'Календарь'), ('notes', 'Заметки')], max_length=50, verbose_name='Тип виджета')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('position_x', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция X')),
                ('position_y', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция Y')),
                ('size', models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Большой')], default='medium', max_length=10, verbose_name='Размер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('settings', models.JSONField(blank=True, null=True, verbose_name='Настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Виджет',
                'verbose_name_plural': 'Виджеты',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='WidgetDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_cache', to='dashboard.widget', verbose_name='Виджет')),
            ],
            options={
                'verbose_name': 'Кэш данных виджета',
                'verbose_name_plural': 'Кэши данных виджетов',
            },
        ),
    ]
