# Generated by Django 5.2 on 2025-04-10 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_certificatetemplate_course_difficulty_level_and_more'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('webinar', 'Вебинар'), ('lecture', 'Лекция'), ('seminar', 'Семинар'), ('consultation', 'Консультация'), ('deadline', 'Дедлайн'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип мероприятия')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на онлайн-мероприятие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное мероприятие')),
                ('max_participants', models.PositiveIntegerField(default=0, help_text='0 - без ограничений', verbose_name='Максимальное количество участников')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='courses.course', verbose_name='Связанный курс')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('goal_type', models.CharField(choices=[('course_completion', 'Завершение курса'), ('certificate', 'Получение сертификата'), ('skill', 'Приобретение навыка'), ('career', 'Карьерная цель'), ('custom', 'Пользовательская цель')], default='custom', max_length=20, verbose_name='Тип цели')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Процент выполнения от 0 до 100', verbose_name='Прогресс выполнения')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='courses.course', verbose_name='Связанный курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Цель студента',
                'verbose_name_plural': 'Цели студентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dashboard.studentgoal', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Шаг цели',
                'verbose_name_plural': 'Шаги целей',
                'ordering': ['goal', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('confirmed', 'Подтвержден'), ('attended', 'Присутствовал'), ('cancelled', 'Отменен')], default='registered', max_length=20, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='Время присутствия')),
                ('feedback', models.TextField(blank=True, verbose_name='Обратная связь')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Оценка мероприятия от 1 до 5', null=True, verbose_name='Оценка')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dashboard.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник мероприятия',
                'verbose_name_plural': 'Участники мероприятий',
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
