# Generated by Django 5.2 on 2025-04-10 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_certificatetemplate_course_difficulty_level_and_more'),
        ('dashboard', '0002_event_studentgoal_goalstep_eventparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'ordering': ['registered_at'], 'verbose_name': 'Участник мероприятия', 'verbose_name_plural': 'Участники мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='goalstep',
            options={'ordering': ['goal', 'order'], 'verbose_name': 'Шаг к цели', 'verbose_name_plural': 'Шаги к целям'},
        ),
        migrations.AddField(
            model_name='goalstep',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='goalstep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичное'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('registered', 'Зарегистрирован'), ('confirmed', 'Подтвержден'), ('attended', 'Присутствовал'), ('absent', 'Отсутствовал'), ('canceled', 'Отменен')], default='registered', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='goalstep',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='goalstep',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studentgoal',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_goals', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='studentgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='studentgoal',
            name='goal_type',
            field=models.CharField(choices=[('course', 'Прохождение курса'), ('exam', 'Подготовка к экзамену'), ('skill', 'Изучение навыка'), ('project', 'Выполнение проекта'), ('custom', 'Другое')], default='custom', max_length=20, verbose_name='Тип цели'),
        ),
        migrations.AlterField(
            model_name='studentgoal',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='studentgoal',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='studentgoal',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studentgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
    ]
