# Generated by Django 5.2 on 2025-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('task_description', models.TextField(blank=True, verbose_name='Описание задания')),
                ('initial_code', models.TextField(blank=True, verbose_name='Начальный код')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное задание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код решения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('checking', 'Проверяется'), ('passed', 'Успешно'), ('failed', 'Неуспешно'), ('error', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('score', models.FloatField(default=0, verbose_name='Оценка')),
                ('feedback', models.TextField(blank=True, verbose_name='Обратная связь')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Отправленное решение',
                'verbose_name_plural': 'Отправленные решения',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, verbose_name='Входные данные')),
                ('expected_output', models.TextField(verbose_name='Ожидаемый результат')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрытый тест')),
            ],
            options={
                'verbose_name': 'Тестовый случай',
                'verbose_name_plural': 'Тестовые случаи',
            },
        ),
    ]
