# Generated by Django 5.2 on 2025-04-09 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Токен устройства')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web Browser')], max_length=10, verbose_name='Тип устройства')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название устройства')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрировано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Токен устройства',
                'verbose_name_plural': 'Токены устройств',
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название канала')),
                ('channel_type', models.CharField(choices=[('web', 'Веб-уведомления'), ('email', 'Адрес электронной почты'), ('push', 'Push-уведомления'), ('telegram', 'Telegram')], max_length=20, verbose_name='Тип канала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Канал уведомлений',
                'verbose_name_plural': 'Каналы уведомлений',
            },
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_8a7c6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_content_702c56_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные'),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='notification',
            name='importance',
            field=models.CharField(choices=[('low', 'Низкая'), ('normal', 'Нормальная'), ('high', 'Высокая'), ('critical', 'Критическая')], default='normal', max_length=10, verbose_name='Важность'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='Push-уведомления'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить тихие часы'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_end',
            field=models.TimeField(default='08:00', verbose_name='Конец тихих часов'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_start',
            field=models.TimeField(default='22:00', verbose_name='Начало тихих часов'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='receive_deadline',
            field=models.BooleanField(default=True, verbose_name='Уведомления о дедлайнах'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='receive_system',
            field=models.BooleanField(default=True, verbose_name='Системные уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Информация'), ('success', 'Успех'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('achievement', 'Достижение'), ('course', 'Курс'), ('lesson', 'Урок'), ('assignment', 'Задание'), ('message', 'Сообщение'), ('system', 'Системное'), ('deadline', 'Дедлайн')], default='info', max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_digest',
            field=models.BooleanField(default=False, verbose_name='Получать дайджест вместо отдельных писем'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email-уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_only_high_priority',
            field=models.BooleanField(default=False, verbose_name='Получать только важные уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_achievement',
            field=models.BooleanField(default=True, verbose_name='Уведомления о достижениях'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_all',
            field=models.BooleanField(default=True, verbose_name='Получать все уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_assignment',
            field=models.BooleanField(default=True, verbose_name='Уведомления о заданиях'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_course',
            field=models.BooleanField(default=True, verbose_name='Уведомления о курсах'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_lesson',
            field=models.BooleanField(default=True, verbose_name='Уведомления об уроках'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_message',
            field=models.BooleanField(default=True, verbose_name='Уведомления о сообщениях'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='preferred_channels',
            field=models.ManyToManyField(blank=True, related_name='user_settings', to='notifications.notificationchannel', verbose_name='Предпочитаемые каналы'),
        ),
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together={('user', 'token')},
        ),
    ]
