# Generated by Django 5.2 on 2025-04-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_8a7c6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_content_702c56_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Информация'), ('success', 'Успех'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('achievement', 'Достижение'), ('course', 'Курс'), ('lesson', 'Урок'), ('assignment', 'Задание'), ('message', 'Сообщение')], default='info', max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_digest',
            field=models.BooleanField(default=False, verbose_name='Получать дайджест вместо отдельных писем'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email-уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_only_high_priority',
            field=models.BooleanField(default=False, verbose_name='Получать только важные уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_achievement',
            field=models.BooleanField(default=True, verbose_name='Уведомления о достижениях'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_all',
            field=models.BooleanField(default=True, verbose_name='Получать все уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_assignment',
            field=models.BooleanField(default=True, verbose_name='Уведомления о заданиях'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_course',
            field=models.BooleanField(default=True, verbose_name='Уведомления о курсах'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_lesson',
            field=models.BooleanField(default=True, verbose_name='Уведомления об уроках'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='receive_message',
            field=models.BooleanField(default=True, verbose_name='Уведомления о сообщениях'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
