# Generated by Django 5.2 on 2025-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_notificatio_user_id_8a7c6b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='push_notifications',
            field=models.BooleanField(default=False, verbose_name='Push-уведомления'),
        ),
    ]
