# Generated by Django 5.2 on 2025-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationsettings_push_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить тихие часы'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец тихих часов'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало тихих часов'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='weekdays_only',
            field=models.BooleanField(default=False, verbose_name='Только по будням'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='weekend_only',
            field=models.BooleanField(default=False, verbose_name='Только по выходным'),
        ),
    ]
