# Generated by Django 5.2 on 2025-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_fix_missing_fields'),
    ]

    operations = [
        # Поля уже существуют, создаем пустую миграцию, чтобы Django считал, что она применена
        migrations.RunSQL(
            sql='-- Эта миграция фиктивная, поскольку поля icon и importance уже существуют',
            reverse_sql='-- Нет необходимости в обратной миграции'
        ),
    ]
